modLoader="javafml" 
loaderVersion="[47,)"
license="GPLv3"
[[mixins]]
  type = "CONFIG"
  config = "soundattract.mixins.json"
[[mods]]
modId="soundattract" 
version="4.0.2" 
logoFile="attract-to-sound-mod-logo.jpg"
displayName="Sound Attract Mod" 
authors="Sylsatra" 
description='''
A mod to make mobs lured into sound.
Also camouflage is a thing.
'''
[[dependencies.soundattract]] 
    modId="forge"
    mandatory=true 
    versionRange="[47,)" 
    ordering="NONE"
    side="BOTH"
[[dependencies.soundattract]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.soundattract]]
    modId="voicechat"
    mandatory=false
    versionRange="[1.20.1-2.5.27,)"
    ordering="NONE"
    side="BOTH"
